export const creditCardPublicSelect = {
  id: true,
  name: true,
  bank: true,
  brand: true,
  last4: true,
  color: true,
  creditLimit: true,
  closingDay: true,
  paymentDueDay: true,
  currency: true,
  isActive: true,
  createdAt: true,
  updatedAt: true,
} as const;
